import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import Sidebar from "@/components/common/sidebar";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Simple Blog App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${geistMono.variable} antialiased`}
            >
                <Header />
                <main className="container flex mx-auto pt-14 min-h-screen">
                    <Sidebar />
                    {children}
                </main>
            </body>
        </html>
    );
}
